### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by IonutAtitienei** [ElanMan/simple-quiz#18]
Hey! I am getting this error:
**The application could not run because of the following error:**

Details

Type: RuntimeException
Message: View cannot render `index.php` because the template does not exist
File: C:\wamp\www\Quiz\vendor\slim\slim\Slim\View.php
Line: 272
Trace

#0 C:\wamp\www\Quiz\vendor\slim\slim\Slim\View.php(255): Slim\View->render('index.php', NULL)
#1 C:\wamp\www\Quiz\vendor\slim\slim\Slim\View.php(243): Slim\View->fetch('index.php', NULL)
#2 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Slim.php(757): Slim\View->display('index.php')
#3 C:\wamp\www\Quiz\routes\public.php(9): Slim\Slim->render('index.php', Array)
#4 [internal function]: {closure}()
#5 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#6 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#7 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#8 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#10 C:\wamp\www\Quiz\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#11 C:\wamp\www\index.php(56): Slim\Slim->run()
#12 {main}

*I do not have any knowledge on composer or slim framework. Could you help me with figuring out what's the problem or guide me where to read more in order to figure this out?*

**Comment by razuro** [comment]
Hi, I think you maybe don't have the mod rewrite turned on. Rather than using WAMP, I recommend you to use [MAMP](https://www.mamp.info/en/downloads/ "Download MAMP"). Less configuration on the apache side.

1. Download this code from SourceForge.
2. Put it in your htdocs directory
3. Load the SQL
4. Rename the SampleConfig.php
5. You should get it running by now

This is just an alternative. If you prefer to configure the mod rewrite, [this](http://stackoverflow.com/questions/21152016/mod-rewrite-on-wamp-2-4 "Mod_rewrite on WAMP 2.4") might help.
